@baseURL = http://localhost:8000
@rootURL = http://localhost:8000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5MDY3ODg4LCJpYXQiOjE3NjkwNjYwODgsImp0aSI6ImFkMTBhNmFjMDEwNjQzNjZhNzcyNmNmMmVjZTc0ZTQzIiwidXNlcl9pZCI6IjEifQ.UETiHcZgSa6Ycc-P5ffn-xejaJlsQ5b20nWuaRkmiak

### Before starting go to /admin
# user: admin
# pass: admin
# go to compliance frameworks +add
# insert any record with dummy data
# to insure that framework with id=1 exist

### to get TOKEN and copy past it to var @token above
POST {{baseURL}}/auth/
Content-Type: application/json

{ "username": "admin", "password": "admin" }

### IMPORTANT: THE PORT OF SERVER DB IS 5432, SO MAKE SURE TO PORT FORWARD YOUR clien_test_db TO 5433:5432
### IMPORTANT: MUST USE host.docker.internal for HOST IN CONNECTION STRING
POST {{rootURL}}/compliance/clientdb/
Content-Type: application/json 
Authorization: Bearer {{token}}

{ "name": "Production Payment DB", "connection_string": "postgresql://myuser:mypassword@host.docker.internal:5433/mydatabase", "description": "Main database storing customer transaction data" }

### Upload schema
POST {{rootURL}}/compliance/clientdbschema/
Content-Type: application/json 
Authorization: Bearer {{token}}

{ "client_db": 1, "schema_json": "your actual schema" }

### start pipeline 
POST {{rootURL}}/compliance/checks/
Content-Type: application/json 
Authorization: Bearer {{token}}

{ "framework": 1, "schema": 1 }

### check it the pipeline is finished and what are the results
GET {{rootURL}}/compliance/assertions/
Content-Type: application/json 
Authorization: Bearer {{token}}

