version: "3.9"

services:
  web:
    build: .
    container_name: compliance_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    container_name: compliance_celery
    command: celery -A watchtower_ce worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7
    container_name: compliance_redis
    ports:
      - "6379:6379"
