# Generated by Django 5.2.9 on 2026-01-30 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('connection_string', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ClientDBSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='compliance.clientdb')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.clientdb')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.clientdbschema')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ComplianceAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_query', models.TextField()),
                ('query_output', models.TextField(blank=True, null=True)),
                ('result', models.BooleanField(null=True)),
                ('recommendation', models.TextField(blank=True, help_text='Human-readable recommendation generated by asynchronous by celerytasks;may be null untill background processing completes ', null=True)),
                ('client_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assertions', to='compliance.clientdb')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assertions', to='compliance.clientdbschema')),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='compliance.compliancecheck')),
                ('compliance_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
