# Generated by Django 5.2.9 on 2026-05-02 22:05

from django.db import migrations


def seed_frameworks(apps, schema_editor):
    ComplianceFramework = apps.get_model("compliance", "ComplianceFramework")

    frameworks = [
        {
            "name": "PCI-DSS",
            "description": "Payment Card Industry Data Security Standard framework for securing cardholder data.",
            "version": "4.0",
        },
        {
            "name": "GDPR",
            "description": "General Data Protection Regulation framework for data privacy and protection in the EU.",
            "version": "2018",
        },
    ]

    for framework in frameworks:
        ComplianceFramework.objects.get_or_create(
            name=framework["name"],
            defaults={
                "description": framework["description"],
                "version": framework["version"],
            },
        )


def remove_frameworks(apps, schema_editor):
    ComplianceFramework = apps.get_model("compliance", "ComplianceFramework")

    ComplianceFramework.objects.filter(name__in=["PCI-DSS", "GDPR"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_frameworks, remove_frameworks),
    ]
