# Generated by Django 5.2.7 on 2025-11-05 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complianceframework",
            options={"ordering": ("id",)},
        ),
    ]
