# Generated by Django 5.2.7 on 2025-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ComplianceStandard',
        ),
    ]
