# Generated by Django 5.2.9 on 2026-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0002_seed_compliance_frameworks"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdb",
            name="frameworks",
            field=models.ManyToManyField(
                blank=True,
                related_name="client_dbs",
                to="compliance.complianceframework",
            ),
        ),
    ]
