# Generated by Django 5.2.7 on 2025-11-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_complianceframework_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('connection_string', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ClientDBSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='compliance.clientdb')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ComplianceAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_query', models.TextField()),
                ('result', models.BooleanField(null=True)),
                ('client_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assertions', to='compliance.clientdb')),
                ('compliance_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='compliance.complianceframework')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assertions', to='compliance.clientdbschema')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
