# Generated by Django 5.2.9 on 2025-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0004_add_compliance_check_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassertion",
            name="recommendation",
            field=models.TextField(null=True),
        ),
    ]
