# Generated by Django 5.2.9 on 2026-01-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0005_complianceassertion_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceassertion",
            name="recommendation",
            field=models.TextField(
                blank=True,
                help_text="Human-readable recommendation generated by asynchronous by celerytasks;may be null untill background processing completes ",
                null=True,
            ),
        ),
    ]
