# Generated by Django 5.2.9 on 2026-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0006_alter_complianceassertion_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdbschema",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientdbschema",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdbschema",
            name="sql_definition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientdbschema",
            name="schema_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
