# Generated by Django 5.2.9 on 2026-02-20 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0007_clientdbschema_description_clientdbschema_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdbschema",
            name="sql_definition",
        ),
    ]
