# Generated by Django 5.2.9 on 2026-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0008_remove_clientdbschema_sql_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdbschema",
            name="sql_definition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
