# Generated by Django 5.2.9 on 2026-03-29 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0009_clientdbschema_sql_definition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientdbschema",
            name="description",
        ),
        migrations.RemoveField(
            model_name="clientdbschema",
            name="name",
        ),
        migrations.RemoveField(
            model_name="clientdbschema",
            name="schema_json",
        ),
    ]
